[package]
name = "pyo3-hint-transpiler"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
walkdir = "2"
toml = "0.9.10"
